trigger:
- main  # Ajusta esto según la rama que desees usar para desencadenar el pipeline

pool:
  vmImage: 'ubuntu-latest'  # Usa una imagen de máquina virtual de Ubuntu

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Job'
  steps:
  - task: NodeTaskRunnerInstaller@0
    inputs:
      nodeVersion: '10'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build  # Si tienes un script de build en tu package.json
    displayName: 'Build the application'

  - script: |
      npm test
    displayName: 'Run tests'

- deployment: VMDeploy
  displayName: 'Deploy to VM'
  environment:
    name: 'helloworld-2-nodejs-20321'
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
            nodeVersion: '10'

        - script: |
            npm install
          displayName: 'Install dependencies on VM'

        - script: |
            npm run start  # Asegúrate de que tu aplicación se inicie correctamente
          displayName: 'Start the application'